layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-feed


include:
  - _pages

markdown: kramdown
theme: null

defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      is_post: true
      layout: post
      permalink: /:year/:month/:day/:title/
  -
    scope:
      path: _pages
      type: pages
    values:
      is_post: false
      layout: default


social_media:
  facebook: carlos.gamino.560
  instagram: moderncarlos
  linkedin: carlos-gamino
  github: cgamino13

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via Aleksandr Hovhannisyan, , and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via .
profPic: "/assets/linkedIn-prof-pic.jpg"
title: Carlos Gamino
email: cgamino@ymail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com